### ISSUE TITLE
parse failed when encountering regex call

### ISSUE THREAD

**Issue by tommy-dong** [samthor/prsr#2]
for example: "new Promise(function(t,n){/^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,6}$/.test(e)?t():n("Invalid email address")})".

**Comment by tommy-dong** [comment]
change 553 line in token.c
      // consume this token as lookup can't know what it was
      if (out->p[0] != '/' || has_value < 0) {
        return ERROR__VALUE;
      } 
to:
      if (has_value < 0) {
        if (out->p[0] != '/' || )
          return ERROR__VALUE;
        else {
          out->type = TOKEN_REGEXP;
          out->len = consume_slash_regexp(out->p);
        }
      }

**Comment by samthor** [comment]
Thanks for the comment and PR. I fixed this [here](https://github.com/samthor/prsr/commit/adcbce27c76ab2a66f386b7e08c66510f3f7bc10).
